default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['ARCHIVE_DATABASE_USER'] %>
  password: <%= ENV['ARCHIVE_DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock

production:
  primary: &primary_production
    <<: *default
    database: archive_production
  queue:
    <<: *primary_production
    database: archive_production_queue
    migrations_paths: db/queue_migrate
