default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['ARCHIVE_DATABASE_USER'] %>
  password: <%= ENV['ARCHIVE_DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock

test:
  primary: &primary_test
    <<: *default
    database: archivedm_test
  queue:
    <<: *primary_test
    database: archivedm_test_queue
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    database: archivedm_production
  queue:
    <<: *primary_production
    database: archivedm_production_queue
    migrations_paths: db/queue_migrate
