 production:
   new_messages:
     class: FetchNewMessagesJob
     schedule: at 3am every day
   new_private_messages:
     class: FetchNewPrivateMessagesJob
     schedule: at 3:05am every day
   new_archived_messages:
     class: FetchNewArchivedMessagesJob
     schedule: at 3:10am every day
