development:
  morphology: stem_en
  max_matches: 10000
  charset_table: non-cjk
  socket: /tmp/development.sphinx.sock
test:
  morphology: stem_en
  max_matches: 10000
  charset_table: non-cjk
  socket: /tmp/test.sphinx.sock
production:
  morphology: stem_en
  max_matches: 10000
  charset_table: non-cjk
  socket: /var/www/archive/shared/tmp/sockets/production.sphinx.sock
  pid_file: /var/www/archive/shared/tmp/searchd.pid
  indices_location: /var/www/archive/shared/db/sphinx
  configuration_file: /var/www/archive/shared/production.sphinx.conf
  binlog_path: /var/www/archive/shared/tmp/binlog
